package com.gvsolutions.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AccountSetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountSetAllPropertiesEquals(AccountSet expected, AccountSet actual) {
        assertAccountSetAutoGeneratedPropertiesEquals(expected, actual);
        assertAccountSetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountSetAllUpdatablePropertiesEquals(AccountSet expected, AccountSet actual) {
        assertAccountSetUpdatableFieldsEquals(expected, actual);
        assertAccountSetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountSetAutoGeneratedPropertiesEquals(AccountSet expected, AccountSet actual) {
        assertThat(actual)
            .as("Verify AccountSet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountSetUpdatableFieldsEquals(AccountSet expected, AccountSet actual) {
        assertThat(actual)
            .as("Verify AccountSet relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getAccountCode()).as("check accountCode").isEqualTo(expected.getAccountCode()))
            .satisfies(a -> assertThat(a.getAccountName()).as("check accountName").isEqualTo(expected.getAccountName()))
            .satisfies(a -> assertThat(a.getAccountType()).as("check accountType").isEqualTo(expected.getAccountType()))
            .satisfies(a -> assertThat(a.getSubCategory()).as("check subCategory").isEqualTo(expected.getSubCategory()))
            .satisfies(a -> assertThat(a.getRemark()).as("check remark").isEqualTo(expected.getRemark()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountSetUpdatableRelationshipsEquals(AccountSet expected, AccountSet actual) {
        // empty method
    }
}
