package com.gvsolutions.domain;

import static com.gvsolutions.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AssetDepreciationHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetDepreciationHistoryAllPropertiesEquals(
        AssetDepreciationHistory expected,
        AssetDepreciationHistory actual
    ) {
        assertAssetDepreciationHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertAssetDepreciationHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetDepreciationHistoryAllUpdatablePropertiesEquals(
        AssetDepreciationHistory expected,
        AssetDepreciationHistory actual
    ) {
        assertAssetDepreciationHistoryUpdatableFieldsEquals(expected, actual);
        assertAssetDepreciationHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetDepreciationHistoryAutoGeneratedPropertiesEquals(
        AssetDepreciationHistory expected,
        AssetDepreciationHistory actual
    ) {
        assertThat(actual)
            .as("Verify AssetDepreciationHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetDepreciationHistoryUpdatableFieldsEquals(
        AssetDepreciationHistory expected,
        AssetDepreciationHistory actual
    ) {
        assertThat(actual)
            .as("Verify AssetDepreciationHistory relevant properties")
            .satisfies(a -> assertThat(a.getAssetRegisterCode()).as("check assetRegisterCode").isEqualTo(expected.getAssetRegisterCode()))
            .satisfies(a -> assertThat(a.getDepreciationDate()).as("check depreciationDate").isEqualTo(expected.getDepreciationDate()))
            .satisfies(a ->
                assertThat(a.getDepreciationAmount())
                    .as("check depreciationAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDepreciationAmount())
            )
            .satisfies(a ->
                assertThat(a.getValueAfterDepreciation())
                    .as("check valueAfterDepreciation")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValueAfterDepreciation())
            )
            .satisfies(a -> assertThat(a.getProcessedBy()).as("check processedBy").isEqualTo(expected.getProcessedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetDepreciationHistoryUpdatableRelationshipsEquals(
        AssetDepreciationHistory expected,
        AssetDepreciationHistory actual
    ) {
        // empty method
    }
}
