package com.gvsolutions.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssetCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetCategoryAllPropertiesEquals(AssetCategory expected, AssetCategory actual) {
        assertAssetCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertAssetCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetCategoryAllUpdatablePropertiesEquals(AssetCategory expected, AssetCategory actual) {
        assertAssetCategoryUpdatableFieldsEquals(expected, actual);
        assertAssetCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetCategoryAutoGeneratedPropertiesEquals(AssetCategory expected, AssetCategory actual) {
        assertThat(actual)
            .as("Verify AssetCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetCategoryUpdatableFieldsEquals(AssetCategory expected, AssetCategory actual) {
        assertThat(actual)
            .as("Verify AssetCategory relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getBranchId()).as("check branchId").isEqualTo(expected.getBranchId()))
            .satisfies(a -> assertThat(a.getAssetCategoryCode()).as("check assetCategoryCode").isEqualTo(expected.getAssetCategoryCode()))
            .satisfies(a -> assertThat(a.getAssetCategoryName()).as("check assetCategoryName").isEqualTo(expected.getAssetCategoryName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetCategoryUpdatableRelationshipsEquals(AssetCategory expected, AssetCategory actual) {
        // empty method
    }
}
