package com.gvsolutions.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssetSubCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetSubCategoryAllPropertiesEquals(AssetSubCategory expected, AssetSubCategory actual) {
        assertAssetSubCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertAssetSubCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetSubCategoryAllUpdatablePropertiesEquals(AssetSubCategory expected, AssetSubCategory actual) {
        assertAssetSubCategoryUpdatableFieldsEquals(expected, actual);
        assertAssetSubCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetSubCategoryAutoGeneratedPropertiesEquals(AssetSubCategory expected, AssetSubCategory actual) {
        assertThat(actual)
            .as("Verify AssetSubCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetSubCategoryUpdatableFieldsEquals(AssetSubCategory expected, AssetSubCategory actual) {
        assertThat(actual)
            .as("Verify AssetSubCategory relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getBranchId()).as("check branchId").isEqualTo(expected.getBranchId()))
            .satisfies(a -> assertThat(a.getAssetCategoryCode()).as("check assetCategoryCode").isEqualTo(expected.getAssetCategoryCode()))
            .satisfies(a ->
                assertThat(a.getAssetSubCategoryCode()).as("check assetSubCategoryCode").isEqualTo(expected.getAssetSubCategoryCode())
            )
            .satisfies(a ->
                assertThat(a.getAssetSubCategoryName()).as("check assetSubCategoryName").isEqualTo(expected.getAssetSubCategoryName())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetSubCategoryUpdatableRelationshipsEquals(AssetSubCategory expected, AssetSubCategory actual) {
        assertThat(actual)
            .as("Verify AssetSubCategory relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
