package com.gvsolutions.domain;

import static com.gvsolutions.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AssetRegisterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetRegisterAllPropertiesEquals(AssetRegister expected, AssetRegister actual) {
        assertAssetRegisterAutoGeneratedPropertiesEquals(expected, actual);
        assertAssetRegisterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetRegisterAllUpdatablePropertiesEquals(AssetRegister expected, AssetRegister actual) {
        assertAssetRegisterUpdatableFieldsEquals(expected, actual);
        assertAssetRegisterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetRegisterAutoGeneratedPropertiesEquals(AssetRegister expected, AssetRegister actual) {
        assertThat(actual)
            .as("Verify AssetRegister auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetRegisterUpdatableFieldsEquals(AssetRegister expected, AssetRegister actual) {
        assertThat(actual)
            .as("Verify AssetRegister relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getBranchId()).as("check branchId").isEqualTo(expected.getBranchId()))
            .satisfies(a -> assertThat(a.getAssetRegisterCode()).as("check assetRegisterCode").isEqualTo(expected.getAssetRegisterCode()))
            .satisfies(a -> assertThat(a.getAssetCategoryCode()).as("check assetCategoryCode").isEqualTo(expected.getAssetCategoryCode()))
            .satisfies(a ->
                assertThat(a.getAssetSubCategoryCode()).as("check assetSubCategoryCode").isEqualTo(expected.getAssetSubCategoryCode())
            )
            .satisfies(a -> assertThat(a.getAssetName()).as("check assetName").isEqualTo(expected.getAssetName()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getPurchaseDate()).as("check purchaseDate").isEqualTo(expected.getPurchaseDate()))
            .satisfies(a ->
                assertThat(a.getPurchaseCost())
                    .as("check purchaseCost")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPurchaseCost())
            )
            .satisfies(a ->
                assertThat(a.getCurrentValue())
                    .as("check currentValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCurrentValue())
            )
            .satisfies(a ->
                assertThat(a.getDepreciationRate())
                    .as("check depreciationRate")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDepreciationRate())
            )
            .satisfies(a ->
                assertThat(a.getAccumulatedDepreciation())
                    .as("check accumulatedDepreciation")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAccumulatedDepreciation())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssetRegisterUpdatableRelationshipsEquals(AssetRegister expected, AssetRegister actual) {
        // empty method
    }
}
