package com.gvsolutions.domain;

import static com.gvsolutions.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BankLedgerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankLedgerAllPropertiesEquals(BankLedger expected, BankLedger actual) {
        assertBankLedgerAutoGeneratedPropertiesEquals(expected, actual);
        assertBankLedgerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankLedgerAllUpdatablePropertiesEquals(BankLedger expected, BankLedger actual) {
        assertBankLedgerUpdatableFieldsEquals(expected, actual);
        assertBankLedgerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankLedgerAutoGeneratedPropertiesEquals(BankLedger expected, BankLedger actual) {
        assertThat(actual)
            .as("Verify BankLedger auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankLedgerUpdatableFieldsEquals(BankLedger expected, BankLedger actual) {
        assertThat(actual)
            .as("Verify BankLedger relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getBankLedgerCode()).as("check bankLedgerCode").isEqualTo(expected.getBankLedgerCode()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getReferenceNo()).as("check referenceNo").isEqualTo(expected.getReferenceNo()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getDepositAmount())
                    .as("check depositAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDepositAmount())
            )
            .satisfies(a ->
                assertThat(a.getWithdrawalAmount())
                    .as("check withdrawalAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getWithdrawalAmount())
            )
            .satisfies(a ->
                assertThat(a.getRunningBalance())
                    .as("check runningBalance")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRunningBalance())
            )
            .satisfies(a -> assertThat(a.getRemark()).as("check remark").isEqualTo(expected.getRemark()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBankLedgerUpdatableRelationshipsEquals(BankLedger expected, BankLedger actual) {
        // empty method
    }
}
