package com.gvsolutions.domain;

import static com.gvsolutions.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BinCardLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBinCardLineAllPropertiesEquals(BinCardLine expected, BinCardLine actual) {
        assertBinCardLineAutoGeneratedPropertiesEquals(expected, actual);
        assertBinCardLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBinCardLineAllUpdatablePropertiesEquals(BinCardLine expected, BinCardLine actual) {
        assertBinCardLineUpdatableFieldsEquals(expected, actual);
        assertBinCardLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBinCardLineAutoGeneratedPropertiesEquals(BinCardLine expected, BinCardLine actual) {
        assertThat(actual)
            .as("Verify BinCardLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBinCardLineUpdatableFieldsEquals(BinCardLine expected, BinCardLine actual) {
        assertThat(actual)
            .as("Verify BinCardLine relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getBranchId()).as("check branchId").isEqualTo(expected.getBranchId()))
            .satisfies(a -> assertThat(a.getInventoryItemCode()).as("check inventoryItemCode").isEqualTo(expected.getInventoryItemCode()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getReferenceNo()).as("check referenceNo").isEqualTo(expected.getReferenceNo()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getQuantityIn())
                    .as("check quantityIn")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getQuantityIn())
            )
            .satisfies(a ->
                assertThat(a.getQuantityOut())
                    .as("check quantityOut")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getQuantityOut())
            )
            .satisfies(a ->
                assertThat(a.getRunningBalance())
                    .as("check runningBalance")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRunningBalance())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBinCardLineUpdatableRelationshipsEquals(BinCardLine expected, BinCardLine actual) {
        // empty method
    }
}
