package com.gvsolutions.domain;

import static com.gvsolutions.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BudgetPlanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBudgetPlanAllPropertiesEquals(BudgetPlan expected, BudgetPlan actual) {
        assertBudgetPlanAutoGeneratedPropertiesEquals(expected, actual);
        assertBudgetPlanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBudgetPlanAllUpdatablePropertiesEquals(BudgetPlan expected, BudgetPlan actual) {
        assertBudgetPlanUpdatableFieldsEquals(expected, actual);
        assertBudgetPlanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBudgetPlanAutoGeneratedPropertiesEquals(BudgetPlan expected, BudgetPlan actual) {
        assertThat(actual)
            .as("Verify BudgetPlan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBudgetPlanUpdatableFieldsEquals(BudgetPlan expected, BudgetPlan actual) {
        assertThat(actual)
            .as("Verify BudgetPlan relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getAccountCode()).as("check accountCode").isEqualTo(expected.getAccountCode()))
            .satisfies(a -> assertThat(a.getBudgetPlanCode()).as("check budgetPlanCode").isEqualTo(expected.getBudgetPlanCode()))
            .satisfies(a -> assertThat(a.getDepartmentName()).as("check departmentName").isEqualTo(expected.getDepartmentName()))
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()))
            .satisfies(a ->
                assertThat(a.getAllocatedAmount())
                    .as("check allocatedAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAllocatedAmount())
            )
            .satisfies(a ->
                assertThat(a.getSpentAmount())
                    .as("check spentAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSpentAmount())
            )
            .satisfies(a ->
                assertThat(a.getRemainingAmount())
                    .as("check remainingAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRemainingAmount())
            )
            .satisfies(a ->
                assertThat(a.getUsedPercentage())
                    .as("check usedPercentage")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getUsedPercentage())
            )
            .satisfies(a -> assertThat(a.getAlertStatus()).as("check alertStatus").isEqualTo(expected.getAlertStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBudgetPlanUpdatableRelationshipsEquals(BudgetPlan expected, BudgetPlan actual) {
        // empty method
    }
}
