package com.gvsolutions.domain;

import static com.gvsolutions.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ChurchStaffAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChurchStaffAllPropertiesEquals(ChurchStaff expected, ChurchStaff actual) {
        assertChurchStaffAutoGeneratedPropertiesEquals(expected, actual);
        assertChurchStaffAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChurchStaffAllUpdatablePropertiesEquals(ChurchStaff expected, ChurchStaff actual) {
        assertChurchStaffUpdatableFieldsEquals(expected, actual);
        assertChurchStaffUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChurchStaffAutoGeneratedPropertiesEquals(ChurchStaff expected, ChurchStaff actual) {
        assertThat(actual)
            .as("Verify ChurchStaff auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChurchStaffUpdatableFieldsEquals(ChurchStaff expected, ChurchStaff actual) {
        assertThat(actual)
            .as("Verify ChurchStaff relevant properties")
            .satisfies(a -> assertThat(a.getStaffCode()).as("check staffCode").isEqualTo(expected.getStaffCode()))
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getFullName()).as("check fullName").isEqualTo(expected.getFullName()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()))
            .satisfies(a -> assertThat(a.getStaffType()).as("check staffType").isEqualTo(expected.getStaffType()))
            .satisfies(a -> assertThat(a.getContactNumber()).as("check contactNumber").isEqualTo(expected.getContactNumber()))
            .satisfies(a ->
                assertThat(a.getHourlyRateOrMonthlySalary())
                    .as("check hourlyRateOrMonthlySalary")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getHourlyRateOrMonthlySalary())
            )
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChurchStaffUpdatableRelationshipsEquals(ChurchStaff expected, ChurchStaff actual) {
        // empty method
    }
}
