package com.gvsolutions.domain;

import static com.gvsolutions.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DonationTrackerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationTrackerAllPropertiesEquals(DonationTracker expected, DonationTracker actual) {
        assertDonationTrackerAutoGeneratedPropertiesEquals(expected, actual);
        assertDonationTrackerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationTrackerAllUpdatablePropertiesEquals(DonationTracker expected, DonationTracker actual) {
        assertDonationTrackerUpdatableFieldsEquals(expected, actual);
        assertDonationTrackerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationTrackerAutoGeneratedPropertiesEquals(DonationTracker expected, DonationTracker actual) {
        assertThat(actual)
            .as("Verify DonationTracker auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationTrackerUpdatableFieldsEquals(DonationTracker expected, DonationTracker actual) {
        assertThat(actual)
            .as("Verify DonationTracker relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getBranchId()).as("check branchId").isEqualTo(expected.getBranchId()))
            .satisfies(a -> assertThat(a.getDonationIdCode()).as("check donationIdCode").isEqualTo(expected.getDonationIdCode()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getDonorNameOrOrg()).as("check donorNameOrOrg").isEqualTo(expected.getDonorNameOrOrg()))
            .satisfies(a -> assertThat(a.getContactDetails()).as("check contactDetails").isEqualTo(expected.getContactDetails()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getPurpose()).as("check purpose").isEqualTo(expected.getPurpose()))
            .satisfies(a -> assertThat(a.getReceivedViaMode()).as("check receivedViaMode").isEqualTo(expected.getReceivedViaMode()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonationTrackerUpdatableRelationshipsEquals(DonationTracker expected, DonationTracker actual) {
        // empty method
    }
}
