package com.gvsolutions.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExpenseCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseCategoryAllPropertiesEquals(ExpenseCategory expected, ExpenseCategory actual) {
        assertExpenseCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertExpenseCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseCategoryAllUpdatablePropertiesEquals(ExpenseCategory expected, ExpenseCategory actual) {
        assertExpenseCategoryUpdatableFieldsEquals(expected, actual);
        assertExpenseCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseCategoryAutoGeneratedPropertiesEquals(ExpenseCategory expected, ExpenseCategory actual) {
        assertThat(actual)
            .as("Verify ExpenseCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseCategoryUpdatableFieldsEquals(ExpenseCategory expected, ExpenseCategory actual) {
        assertThat(actual)
            .as("Verify ExpenseCategory relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getBranchId()).as("check branchId").isEqualTo(expected.getBranchId()))
            .satisfies(a -> assertThat(a.getCategoryCode()).as("check categoryCode").isEqualTo(expected.getCategoryCode()))
            .satisfies(a -> assertThat(a.getCategoryName()).as("check categoryName").isEqualTo(expected.getCategoryName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseCategoryUpdatableRelationshipsEquals(ExpenseCategory expected, ExpenseCategory actual) {
        // empty method
    }
}
