package com.gvsolutions.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExpenseSubCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseSubCategoryAllPropertiesEquals(ExpenseSubCategory expected, ExpenseSubCategory actual) {
        assertExpenseSubCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertExpenseSubCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseSubCategoryAllUpdatablePropertiesEquals(ExpenseSubCategory expected, ExpenseSubCategory actual) {
        assertExpenseSubCategoryUpdatableFieldsEquals(expected, actual);
        assertExpenseSubCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseSubCategoryAutoGeneratedPropertiesEquals(ExpenseSubCategory expected, ExpenseSubCategory actual) {
        assertThat(actual)
            .as("Verify ExpenseSubCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseSubCategoryUpdatableFieldsEquals(ExpenseSubCategory expected, ExpenseSubCategory actual) {
        assertThat(actual)
            .as("Verify ExpenseSubCategory relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getBranchId()).as("check branchId").isEqualTo(expected.getBranchId()))
            .satisfies(a -> assertThat(a.getCategoryCode()).as("check categoryCode").isEqualTo(expected.getCategoryCode()))
            .satisfies(a -> assertThat(a.getSubCategoryCode()).as("check subCategoryCode").isEqualTo(expected.getSubCategoryCode()))
            .satisfies(a -> assertThat(a.getSubCategoryName()).as("check subCategoryName").isEqualTo(expected.getSubCategoryName()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseSubCategoryUpdatableRelationshipsEquals(ExpenseSubCategory expected, ExpenseSubCategory actual) {
        assertThat(actual)
            .as("Verify ExpenseSubCategory relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
