package com.gvsolutions.domain;

import static com.gvsolutions.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ExpenseEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseEntryAllPropertiesEquals(ExpenseEntry expected, ExpenseEntry actual) {
        assertExpenseEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertExpenseEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseEntryAllUpdatablePropertiesEquals(ExpenseEntry expected, ExpenseEntry actual) {
        assertExpenseEntryUpdatableFieldsEquals(expected, actual);
        assertExpenseEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseEntryAutoGeneratedPropertiesEquals(ExpenseEntry expected, ExpenseEntry actual) {
        assertThat(actual)
            .as("Verify ExpenseEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseEntryUpdatableFieldsEquals(ExpenseEntry expected, ExpenseEntry actual) {
        assertThat(actual)
            .as("Verify ExpenseEntry relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getAccountCode()).as("check accountCode").isEqualTo(expected.getAccountCode()))
            .satisfies(a -> assertThat(a.getExpenseCode()).as("check expenseCode").isEqualTo(expected.getExpenseCode()))
            .satisfies(a ->
                assertThat(a.getExpenseCategoryCode()).as("check expenseCategoryCode").isEqualTo(expected.getExpenseCategoryCode())
            )
            .satisfies(a ->
                assertThat(a.getExpenseSubCategoryCode()).as("check expenseSubCategoryCode").isEqualTo(expected.getExpenseSubCategoryCode())
            )
            .satisfies(a -> assertThat(a.getCreatedByUsername()).as("check createdByUsername").isEqualTo(expected.getCreatedByUsername()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getVoucherNo()).as("check voucherNo").isEqualTo(expected.getVoucherNo()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getPaymentMode()).as("check paymentMode").isEqualTo(expected.getPaymentMode()))
            .satisfies(a -> assertThat(a.getApprovalStatus()).as("check approvalStatus").isEqualTo(expected.getApprovalStatus()))
            .satisfies(a -> assertThat(a.getApprovedBy()).as("check approvedBy").isEqualTo(expected.getApprovedBy()))
            .satisfies(a -> assertThat(a.getVendor()).as("check vendor").isEqualTo(expected.getVendor()))
            .satisfies(a -> assertThat(a.getSyncStatus()).as("check syncStatus").isEqualTo(expected.getSyncStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExpenseEntryUpdatableRelationshipsEquals(ExpenseEntry expected, ExpenseEntry actual) {
        // empty method
    }
}
