package com.gvsolutions.domain;

import static com.gvsolutions.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class IncomeEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeEntryAllPropertiesEquals(IncomeEntry expected, IncomeEntry actual) {
        assertIncomeEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertIncomeEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeEntryAllUpdatablePropertiesEquals(IncomeEntry expected, IncomeEntry actual) {
        assertIncomeEntryUpdatableFieldsEquals(expected, actual);
        assertIncomeEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeEntryAutoGeneratedPropertiesEquals(IncomeEntry expected, IncomeEntry actual) {
        assertThat(actual)
            .as("Verify IncomeEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeEntryUpdatableFieldsEquals(IncomeEntry expected, IncomeEntry actual) {
        assertThat(actual)
            .as("Verify IncomeEntry relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getAccountCode()).as("check accountCode").isEqualTo(expected.getAccountCode()))
            .satisfies(a -> assertThat(a.getIncomeCode()).as("check incomeCode").isEqualTo(expected.getIncomeCode()))
            .satisfies(a -> assertThat(a.getCreatedByUsername()).as("check createdByUsername").isEqualTo(expected.getCreatedByUsername()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getReceiptNo()).as("check receiptNo").isEqualTo(expected.getReceiptNo()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getIncomeType()).as("check incomeType").isEqualTo(expected.getIncomeType()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getPaymentMethod()).as("check paymentMethod").isEqualTo(expected.getPaymentMethod()))
            .satisfies(a -> assertThat(a.getReceivablePerson()).as("check receivablePerson").isEqualTo(expected.getReceivablePerson()))
            .satisfies(a -> assertThat(a.getReceivedBy()).as("check receivedBy").isEqualTo(expected.getReceivedBy()))
            .satisfies(a -> assertThat(a.getSyncStatus()).as("check syncStatus").isEqualTo(expected.getSyncStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIncomeEntryUpdatableRelationshipsEquals(IncomeEntry expected, IncomeEntry actual) {
        // empty method
    }
}
