package com.gvsolutions.domain;

import static com.gvsolutions.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class InventoryItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryItemAllPropertiesEquals(InventoryItem expected, InventoryItem actual) {
        assertInventoryItemAutoGeneratedPropertiesEquals(expected, actual);
        assertInventoryItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryItemAllUpdatablePropertiesEquals(InventoryItem expected, InventoryItem actual) {
        assertInventoryItemUpdatableFieldsEquals(expected, actual);
        assertInventoryItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryItemAutoGeneratedPropertiesEquals(InventoryItem expected, InventoryItem actual) {
        assertThat(actual)
            .as("Verify InventoryItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryItemUpdatableFieldsEquals(InventoryItem expected, InventoryItem actual) {
        assertThat(actual)
            .as("Verify InventoryItem relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getBranchId()).as("check branchId").isEqualTo(expected.getBranchId()))
            .satisfies(a -> assertThat(a.getInventoryItemCode()).as("check inventoryItemCode").isEqualTo(expected.getInventoryItemCode()))
            .satisfies(a -> assertThat(a.getItemName()).as("check itemName").isEqualTo(expected.getItemName()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a ->
                assertThat(a.getQuantity()).as("check quantity").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQuantity())
            )
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            )
            .satisfies(a ->
                assertThat(a.getRunningStockCount())
                    .as("check runningStockCount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRunningStockCount())
            )
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryItemUpdatableRelationshipsEquals(InventoryItem expected, InventoryItem actual) {
        // empty method
    }
}
