package com.gvsolutions.domain;

import static com.gvsolutions.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LiabilityLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLiabilityLogAllPropertiesEquals(LiabilityLog expected, LiabilityLog actual) {
        assertLiabilityLogAutoGeneratedPropertiesEquals(expected, actual);
        assertLiabilityLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLiabilityLogAllUpdatablePropertiesEquals(LiabilityLog expected, LiabilityLog actual) {
        assertLiabilityLogUpdatableFieldsEquals(expected, actual);
        assertLiabilityLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLiabilityLogAutoGeneratedPropertiesEquals(LiabilityLog expected, LiabilityLog actual) {
        assertThat(actual)
            .as("Verify LiabilityLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLiabilityLogUpdatableFieldsEquals(LiabilityLog expected, LiabilityLog actual) {
        assertThat(actual)
            .as("Verify LiabilityLog relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getBranchId()).as("check branchId").isEqualTo(expected.getBranchId()))
            .satisfies(a -> assertThat(a.getLiabilityCode()).as("check liabilityCode").isEqualTo(expected.getLiabilityCode()))
            .satisfies(a -> assertThat(a.getLoanFrom()).as("check loanFrom").isEqualTo(expected.getLoanFrom()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getLiabilityType()).as("check liabilityType").isEqualTo(expected.getLiabilityType()))
            .satisfies(a ->
                assertThat(a.getTotalLoanAmount())
                    .as("check totalLoanAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalLoanAmount())
            )
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a ->
                assertThat(a.getInterestPercentage())
                    .as("check interestPercentage")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getInterestPercentage())
            )
            .satisfies(a ->
                assertThat(a.getMonthlyPaymentAmount())
                    .as("check monthlyPaymentAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMonthlyPaymentAmount())
            )
            .satisfies(a ->
                assertThat(a.getPrincipalPaid())
                    .as("check principalPaid")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrincipalPaid())
            )
            .satisfies(a ->
                assertThat(a.getBalanceToPay())
                    .as("check balanceToPay")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBalanceToPay())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLiabilityLogUpdatableRelationshipsEquals(LiabilityLog expected, LiabilityLog actual) {
        // empty method
    }
}
