package com.gvsolutions.domain;

import static com.gvsolutions.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MaintenanceLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceLogAllPropertiesEquals(MaintenanceLog expected, MaintenanceLog actual) {
        assertMaintenanceLogAutoGeneratedPropertiesEquals(expected, actual);
        assertMaintenanceLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceLogAllUpdatablePropertiesEquals(MaintenanceLog expected, MaintenanceLog actual) {
        assertMaintenanceLogUpdatableFieldsEquals(expected, actual);
        assertMaintenanceLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceLogAutoGeneratedPropertiesEquals(MaintenanceLog expected, MaintenanceLog actual) {
        assertThat(actual)
            .as("Verify MaintenanceLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceLogUpdatableFieldsEquals(MaintenanceLog expected, MaintenanceLog actual) {
        assertThat(actual)
            .as("Verify MaintenanceLog relevant properties")
            .satisfies(a -> assertThat(a.getMaintenanceLogCode()).as("check maintenanceLogCode").isEqualTo(expected.getMaintenanceLogCode())
            )
            .satisfies(a -> assertThat(a.getLogDate()).as("check logDate").isEqualTo(expected.getLogDate()))
            .satisfies(a -> assertThat(a.getLogType()).as("check logType").isEqualTo(expected.getLogType()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCost()).as("check cost").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCost()))
            .satisfies(a -> assertThat(a.getVendor()).as("check vendor").isEqualTo(expected.getVendor()))
            .satisfies(a -> assertThat(a.getNextServiceDate()).as("check nextServiceDate").isEqualTo(expected.getNextServiceDate()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaintenanceLogUpdatableRelationshipsEquals(MaintenanceLog expected, MaintenanceLog actual) {
        assertThat(actual)
            .as("Verify MaintenanceLog relationships")
            .satisfies(a -> assertThat(a.getAsset()).as("check asset").isEqualTo(expected.getAsset()));
    }
}
