package com.gvsolutions.domain;

import static com.gvsolutions.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PettyCashLedgerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPettyCashLedgerAllPropertiesEquals(PettyCashLedger expected, PettyCashLedger actual) {
        assertPettyCashLedgerAutoGeneratedPropertiesEquals(expected, actual);
        assertPettyCashLedgerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPettyCashLedgerAllUpdatablePropertiesEquals(PettyCashLedger expected, PettyCashLedger actual) {
        assertPettyCashLedgerUpdatableFieldsEquals(expected, actual);
        assertPettyCashLedgerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPettyCashLedgerAutoGeneratedPropertiesEquals(PettyCashLedger expected, PettyCashLedger actual) {
        assertThat(actual)
            .as("Verify PettyCashLedger auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPettyCashLedgerUpdatableFieldsEquals(PettyCashLedger expected, PettyCashLedger actual) {
        assertThat(actual)
            .as("Verify PettyCashLedger relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getPettyCashCode()).as("check pettyCashCode").isEqualTo(expected.getPettyCashCode()))
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getPettyCashVoucherNo()).as("check pettyCashVoucherNo").isEqualTo(expected.getPettyCashVoucherNo())
            )
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getCashIn()).as("check cashIn").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCashIn())
            )
            .satisfies(a ->
                assertThat(a.getCashOut()).as("check cashOut").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCashOut())
            )
            .satisfies(a ->
                assertThat(a.getRunningBalance())
                    .as("check runningBalance")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRunningBalance())
            )
            .satisfies(a -> assertThat(a.getLinkedAccountCode()).as("check linkedAccountCode").isEqualTo(expected.getLinkedAccountCode()))
            .satisfies(a -> assertThat(a.getReferenceNo()).as("check referenceNo").isEqualTo(expected.getReferenceNo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPettyCashLedgerUpdatableRelationshipsEquals(PettyCashLedger expected, PettyCashLedger actual) {
        // empty method
    }
}
