package com.gvsolutions.domain;

import static com.gvsolutions.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SalaryPayoutAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaryPayoutAllPropertiesEquals(SalaryPayout expected, SalaryPayout actual) {
        assertSalaryPayoutAutoGeneratedPropertiesEquals(expected, actual);
        assertSalaryPayoutAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaryPayoutAllUpdatablePropertiesEquals(SalaryPayout expected, SalaryPayout actual) {
        assertSalaryPayoutUpdatableFieldsEquals(expected, actual);
        assertSalaryPayoutUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaryPayoutAutoGeneratedPropertiesEquals(SalaryPayout expected, SalaryPayout actual) {
        assertThat(actual)
            .as("Verify SalaryPayout auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaryPayoutUpdatableFieldsEquals(SalaryPayout expected, SalaryPayout actual) {
        assertThat(actual)
            .as("Verify SalaryPayout relevant properties")
            .satisfies(a -> assertThat(a.getBranchCode()).as("check branchCode").isEqualTo(expected.getBranchCode()))
            .satisfies(a -> assertThat(a.getBranchId()).as("check branchId").isEqualTo(expected.getBranchId()))
            .satisfies(a -> assertThat(a.getSalaryPayoutCode()).as("check salaryPayoutCode").isEqualTo(expected.getSalaryPayoutCode()))
            .satisfies(a -> assertThat(a.getStaffCode()).as("check staffCode").isEqualTo(expected.getStaffCode()))
            .satisfies(a -> assertThat(a.getPayPeriod()).as("check payPeriod").isEqualTo(expected.getPayPeriod()))
            .satisfies(a ->
                assertThat(a.getBaseSalary())
                    .as("check baseSalary")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBaseSalary())
            )
            .satisfies(a ->
                assertThat(a.getAllowances())
                    .as("check allowances")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAllowances())
            )
            .satisfies(a ->
                assertThat(a.getDeductions())
                    .as("check deductions")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDeductions())
            )
            .satisfies(a ->
                assertThat(a.getNetPay()).as("check netPay").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getNetPay())
            )
            .satisfies(a -> assertThat(a.getPayoutDate()).as("check payoutDate").isEqualTo(expected.getPayoutDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSalaryPayoutUpdatableRelationshipsEquals(SalaryPayout expected, SalaryPayout actual) {
        // empty method
    }
}
